# Generated by Django 3.0.3 on 2020-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('pictureId', models.AutoField(primary_key=True, serialize=True)),
            ],
        ),
    ]
