# Generated by Django 3.0.3 on 2020-02-17 13:03

from django.db import migrations, models
from django_add_default_value import AddDefaultValue



class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='pictureData',
            field=models.TextField(default="https://static.wixstatic.com/media/b77fe464cfc445da9003a5383a3e1acf.jpg"),
        ),
        migrations.AddField(
            model_name='pictures',
            name='word',
            field=models.CharField(default='blank', max_length=255),
        ),
         AddDefaultValue(
            model_name='pictures',
            name='pictureData', 
            value="https://static.wixstatic.com/media/b77fe464cfc445da9003a5383a3e1acf.jpg"
        )
    ]
