# Generated by Django 3.0.3 on 2020-02-17 14:46

from django.db import migrations, models
import django.db.models.deletion
from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20200217_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(
                    max_length=50, primary_key=True, serialize=False)),
                ('avatarUrl', models.CharField(
                    default='https://www.kindpng.com/picc/m/421-4212275_transparent-default-avatar-png-avatar-img-png-download.png', max_length=255)),
                ('language', models.CharField(default='english', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('imgCount', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='schema.Pictures')),
            ],
        ),
        AddDefaultValue(
            model_name='Users',
            name='score', value=0

        ),
        AddDefaultValue(
            model_name='Users',
            name='imgCount_id', value=1
        ),
        AddDefaultValue(
            model_name='Users',
            name='avatarUrl', value='https://www.kindpng.com/picc/m/421-4212275_transparent-default-avatar-png-avatar-img-png-download.png'

        ),
        AddDefaultValue(
            model_name='Users',
            name='language', value='english'

        )
    ]
