# Generated by Django 3.0.3 on 2020-02-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='imgCount',
            new_name='img',
        ),
    ]
