# Generated by Django 3.0.3 on 2020-02-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20200217_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.Pictures'),
        ),
    ]
